openapi: 3.0.0
info:
  contact:
    email: valentino.lauciani@ingv.it
    name: Valentino Lauciani
  description: |2-


    The **fdsnws-event** web service returns event (earthquake) information from the catalogs [ISIDe](http://iside.rm.ingv.it/).

    The results are returnd as XML in [QuakeML](https://quake.ethz.ch/quakeml) format ([schema](https://quake.ethz.ch/quakeml/docs/xml?action=AttachFile&do=get&target=QuakeML-BED-1.2.xsd)), but may also be requested in text formats.


    # Query Usage


    To retrieve data from the event service, submit a request by either of the methods below:

      - _via HTTP GET_: Provide a series of parameter-value pairs in the URL that specify the start-time and end-time, along with the desired network(s) and others param(s). Please refer to the table below titled "Detailed Descriptions of each Query Parameter" for usage details. Each parameter-value pair should be separated by an ampersand **&**, and with no space. A GET request may take the following general form:

    ```

    /query? [geographic-constraints] [depth-constraints] [temporal-constraints] [magnitude-constraints] [format-option]

    ```


    or

    ```

    /query? (id-options) [includeallmagnitudes] [includeallorigins] [includearrivals] [includeallstationsmagnitudes] [format-option]

    ```


    where

    ```

    id-options              ::  eventid= OR originid= OR magnitudeid= OR focalmechanismid=

    geographic-constraints  ::  [boundaries-rect] OR [boundaries-radial]

    boundaries-rect         ::  [minlat=] [maxlat=] [minlon=] [maxlon=]

    boundaries-radial       ::  [lat=&lon=&(maxradius= | maxradiuskm=)] [minradius= | minradiuskm=]

    depth-constraints       ::  [mindepth=] [maxdepth=]

    temporal-constraints    ::  [starttime=] [endtime=]

    magnitude-constraints   ::  [minmag=] [maxmag=] [magnitudetype=]

    misc-parameters         ::  [limit=] [offset=] [orderby=] [includeallmagnitude=]
                                [includearrivals=] [includeallorigins=] [includeallstationsmagnitudes=]
    format-option           ::  [format=]


      (..) required parameter
      [..] optional parameter
    ```


    # Sample Queries:
      - [http://webservices.ingv.it/fdsnws/event/1/query?starttime=2012-05-29T00:00:00&endtime=2012-05-29T23:59:59](http://webservices.ingv.it/fdsnws/event/1/query?starttime=2012-05-29T00:00:00&endtime=2012-05-29T23:59:59)
      - [http://webservices.ingv.it/fdsnws/event/1/query?starttime=2010-05-29T00:00:00&endtime=2012-05-29T23:59:58&limit=10&offset=2](http://webservices.ingv.it/fdsnws/event/1/query?starttime=2010-05-29T00:00:00&endtime=2012-05-29T23:59:58&limit=10&offset=2)
      - [http://webservices.ingv.it/fdsnws/event/1/query?starttime=2012-05-29T00:00:00&endtime=2012-05-29T23:59:59&format=text](http://webservices.ingv.it/fdsnws/event/1/query?starttime=2012-05-29T00:00:00&endtime=2012-05-29T23:59:59&format=text) (text format)
      - [http://webservices.ingv.it/fdsnws/event/1/query?eventId=841091&includeallmagnitudes=true&includeallorigins=true&includearrivals=true&includeallstationsmagnitudes=true](http://webservices.ingv.it/fdsnws/event/1/query?eventId=841091&includeallmagnitudes=true&includeallorigins=true&includearrivals=true&includeallstationsmagnitudes=true)


     Find out more about FDSN Web Service Specifications http://www.fdsn.org/webservices/
  license:
    name: Creative Commons Attribution 4.0 International
    url: http://creativecommons.org/licenses/by/4.0/
  termsOfService: http://www.fdsn.org/webservices/
  title: INGV ONT FDSNWS event Web Service Documentation
  version: 1.1.50
  x-api-id: 4a4a81b3-f01f-4316-94f1-e150718aed2b
  x-logo: http://webservices.ingv.it/ingv_logo.png
  x-summary: fdsnws-event
servers:
- description: Production
  url: http://webservices.ingv.it/fdsnws/event/1
tags:
- description: ''
  externalDocs:
    description: Find out more
    url: https://quake.ethz.ch/quakeml/
  name: fdsnws-event-1.1
paths:
  /application.wadl:
    get:
      description: Returns application.wadl file content
      responses:
        '200':
          content:
            application/xml:
              schema:
                additionalProperties:
                  format: int32
                  type: integer
                type: object
          description: Successful request, results follow
      summary: Get application.wadl
      tags:
      - fdsnws-event-1.1
  /query:
    get:
      description: Returns a QuakeML message with the following schema https://quake.ethz.ch/quakeml/
      parameters:
      - $ref: '#/components/parameters/starttimeParameter'
      - $ref: '#/components/parameters/endtimeParameter'
      - $ref: '#/components/parameters/minlatParameter'
      - $ref: '#/components/parameters/maxlatParameter'
      - $ref: '#/components/parameters/minlonParameter'
      - $ref: '#/components/parameters/maxlonParameter'
      - $ref: '#/components/parameters/latParameter'
      - $ref: '#/components/parameters/lonParameter'
      - $ref: '#/components/parameters/minradiusParameter'
      - $ref: '#/components/parameters/maxradiusParameter'
      - $ref: '#/components/parameters/minradiuskmParameter'
      - $ref: '#/components/parameters/maxradiuskmParameter'
      - $ref: '#/components/parameters/mindepthParameter'
      - $ref: '#/components/parameters/maxdepthParameter'
      - $ref: '#/components/parameters/orderbyParameter'
      - $ref: '#/components/parameters/limitParameter'
      - $ref: '#/components/parameters/offsetParameter'
      - $ref: '#/components/parameters/updatedafterParameter'
      - $ref: '#/components/parameters/formatParameter'
      - $ref: '#/components/parameters/eventidParameter'
      - $ref: '#/components/parameters/includealloriginsParameter'
      - $ref: '#/components/parameters/includeallmagnitudesParameter'
      - $ref: '#/components/parameters/includeallstationsmagnitudesParameter'
      - $ref: '#/components/parameters/includearrivalsParameter'
      responses:
        '200':
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/QuakeMLResponse'
            text/plain:
              schema:
                $ref: '#/components/schemas/QuakeMLResponse'
          description: Successful request, results follow
          headers:
            X-RateLimit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
        '204':
          $ref: '#/components/responses/204NoContent'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '404':
          $ref: '#/components/responses/404NotFound'
        '429':
          $ref: '#/components/responses/429TooManyRequests'
        '503':
          $ref: '#/components/responses/503ServiceUnavailable'
        default:
          $ref: '#/components/responses/default'
      summary: Get QuakeML
      tags:
      - fdsnws-event-1.1
  /version:
    get:
      description: Returns a string containing QuakeML version
      responses:
        '200':
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/VersionResponse'
          description: Successful request, results follow
      summary: Get QuakeML version
      tags:
      - fdsnws-event-1.1
components:
  headers:
    Retry-After:
      description: |-
        Retry contacting the endpoint *at least* after seconds.
        See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        format: int32
        type: integer
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period
      schema:
        format: int32
        type: integer
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period
      schema:
        format: int32
        type: integer
    X-RateLimit-Reset:
      description: The number of seconds left in the current period
      schema:
        format: int32
        type: integer
  parameters:
    endtimeParameter:
      description: Select date end. - [ **YYYY-MM-DDThh:mm:ss** | **YYYY-MM-DD** ]
        (ex. 2013-02-19T17:06:38)
      in: query
      name: endtime
      required: false
      schema:
        format: date-time
        items:
          type: string
        type: string
    eventidParameter:
      description: Retrieve an event based on the unique INGV event id.
      in: query
      name: eventid
      required: false
      schema:
        items:
          type: integer
        type: integer
    formatParameter:
      description: Specify output format.
      in: query
      name: format
      required: false
      schema:
        default: xml
        enum:
        - xml
        - text
        items:
          type: string
        type: string
    includeallmagnitudesParameter:
      description: Is used to retrive all magnitudes associated with each event.
      in: query
      name: includeallmagnitudes
      required: false
      schema:
        default: false
        items:
          type: boolean
        type: boolean
    includealloriginsParameter:
      description: Is used to retrive all origins associated with each event.
      in: query
      name: includeallorigins
      required: false
      schema:
        default: false
        items:
          type: boolean
        type: boolean
    includeallstationsmagnitudesParameter:
      description: Is used to retrive all stations magnitudes associated with each
        hypocenter.
      in: query
      name: includeallstationsmagnitudes
      required: false
      schema:
        default: false
        items:
          type: boolean
        type: boolean
    includearrivalsParameter:
      description: Is used to retrive any associated phase arrival information for
        each event.
      in: query
      name: includearrivals
      required: false
      schema:
        default: false
        items:
          type: boolean
        type: boolean
    latParameter:
      description: Specify the central latitude point for a radial search.
      in: query
      name: lat
      required: false
      schema:
        format: double
        items:
          type: string
        type: number
    limitParameter:
      description: Limit the results to the specified number of events.
      in: query
      name: limit
      required: false
      schema:
        format: integer
        items:
          type: string
        type: number
    lonParameter:
      description: Specify the central longitude point for a radial search.
      in: query
      name: lat
      required: false
      schema:
        format: double
        items:
          type: string
        type: number
    maxdepthParameter:
      description: Specify maximum depth (kilometers), values increase positively
        with depth.
      in: query
      name: maxdepth
      required: false
      schema:
        format: double
        items:
          type: string
        type: number
    maxlatParameter:
      description: Specify northern boundary for search.
      in: query
      name: maxlat
      required: false
      schema:
        format: double
        items:
          type: string
        type: number
    maxlonParameter:
      description: Specify eastern boundary for search.
      in: query
      name: maxlon
      required: false
      schema:
        format: double
        items:
          type: string
        type: number
    maxradiusParameter:
      description: Specify maximum distance from the geographic point defined by latitude
        and longitude. Degrees.
      in: query
      name: maxradius
      required: false
      schema:
        format: double
        items:
          type: string
        type: number
    maxradiuskmParameter:
      description: Specify maximum distance from the geographic point defined by latitude
        and longitude. Kilometers. **This is an INGV extension to the FDSN specification.**
      in: query
      name: maxradiuskm
      required: false
      schema:
        format: double
        items:
          type: string
        type: number
    mindepthParameter:
      description: Specify minimum depth (kilometers), values increase positively
        with depth.
      in: query
      name: mindepth
      required: false
      schema:
        format: double
        items:
          type: string
        type: number
    minlatParameter:
      description: Specify southern boundary for search.
      in: query
      name: minlat
      required: false
      schema:
        format: double
        items:
          type: string
        type: number
    minlonParameter:
      description: Specify western boundary for search.
      in: query
      name: minlon
      required: false
      schema:
        format: double
        items:
          type: string
        type: number
    minradiusParameter:
      description: Specify minimum distance from the geographic point defined by latitude
        and longitude. Degrees.
      in: query
      name: minradius
      required: false
      schema:
        format: double
        items:
          type: string
        type: number
    minradiuskmParameter:
      description: Specify minimum distance from the geographic point defined by latitude
        and longitude. Kilometers. **This is an INGV extension to the FDSN specification.**
      in: query
      name: minradiuskm
      required: false
      schema:
        format: double
        items:
          type: string
        type: number
    offsetParameter:
      description: Return results starting at the event count specified.
      in: query
      name: offset
      required: false
      schema:
        format: integer
        items:
          type: string
        type: number
    orderbyParameter:
      description: Is used to order the output.
      in: query
      name: orderby
      required: false
      schema:
        default: time
        enum:
        - time
        - time-asc
        - magnitude
        - magnitude-asc
        items:
          type: string
        type: string
    starttimeParameter:
      description: Select date start. - [ **YYYY-MM-DDThh:mm:ss** | **YYYY-MM-DD**
        ] (ex. 2013-02-18T15:06:38)
      in: query
      name: starttime
      required: false
      schema:
        format: date-time
        items:
          type: string
        type: string
    updatedafterParameter:
      description: Limit to events updated after the specified time (useful for synchronizing
        events).
      in: query
      name: updatedafter
      required: false
      schema:
        format: date-time
        items:
          type: string
        type: string
  responses:
    204NoContent:
      description: Request was properly formatted and submitted but no data matches
        the selection
      headers:
        X-RateLimit-Limit:
          $ref: '#/components/headers/X-RateLimit-Limit'
        X-RateLimit-Remaining:
          $ref: '#/components/headers/X-RateLimit-Remaining'
        X-RateLimit-Reset:
          $ref: '#/components/headers/X-RateLimit-Reset'
    400BadRequest:
      content:
        text/plain:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
      description: Bad Request
    404NotFound:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
      description: Not Found
    429TooManyRequests:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
      description: Too many requests
      headers:
        Retry-After:
          $ref: '#/components/headers/Retry-After'
        X-RateLimit-Limit:
          $ref: '#/components/headers/X-RateLimit-Limit'
        X-RateLimit-Remaining:
          $ref: '#/components/headers/X-RateLimit-Remaining'
        X-RateLimit-Reset:
          $ref: '#/components/headers/X-RateLimit-Reset'
    503ServiceUnavailable:
      content:
        text/plain:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
      description: Service Unavailable
      headers:
        Retry-After:
          $ref: '#/components/headers/Retry-After'
    default:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
      description: Unexpected error
  schemas:
    ErrorResponse:
      example: 'Error CODE: SIMPLE ERROR DESCRIPTION ...'
      type: string
    Problem:
      properties:
        detail:
          description: |
            A human readable explanation specific to this occurrence of the
            problem. You MUST NOT expose internal informations, personal
            data or implementation details through this field.
          example: Request took too long to complete.
          type: string
        instance:
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
          format: uri
          type: string
        status:
          description: |
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          example: 503
          exclusiveMaximum: true
          format: int32
          maximum: 600
          minimum: 100
          type: integer
        title:
          description: |
            A short, summary of the problem type. Written in english and readable
            for engineers (usually not suited for non technical stakeholders and
            not localized); example: Service Unavailable
          type: string
        type:
          default: about:blank
          description: |
            An absolute URI that identifies the problem type.  When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          example: https://tools.ietf.org/html/rfc7231#section-6.6.4
          format: uri
          type: string
      type: object
    QuakeMLResponse:
      xml:
        namespace: https://quake.ethz.ch/quakeml/
    VersionResponse:
      example: 1.1.50
      type: string
