openapi: 3.0.0
info:
  contact:
    email: valentino.lauciani@ingv.it
    name: FIXME
    url: FIXME
  description: "\n\nThe **fdsnws-event** web service returns event (earthquake) information\
    \ from the catalogs [ISIDe](http://iside.rm.ingv.it/).\n\nThe results are returnd\
    \ as XML in [QuakeML](https://quake.ethz.ch/quakeml) format ([schema](https://quake.ethz.ch/quakeml/docs/xml?action=AttachFile&do=get&target=QuakeML-BED-1.2.xsd)),\
    \ but may also be requested in text formats.\n\n\n# Query Usage\n\n\nTo retrieve\
    \ data from the event service, submit a request by either of the methods below:\n\
    \n  - _via HTTP GET_: Provide a series of parameter-value pairs in the URL that\
    \ specify the start-time and end-time, along with the desired network(s) and others\
    \ param(s). Please refer to the table below titled \"Detailed Descriptions of\
    \ each Query Parameter\" for usage details. Each parameter-value pair should be\
    \ separated by an ampersand **&**, and with no space. A GET request may take the\
    \ following general form:\n\n```\n\n/query? [geographic-constraints] [depth-constraints]\
    \ [temporal-constraints] [magnitude-constraints] [format-option]\n\n```\n\n\n\
    or\n\n```\n\n/query? (id-options) [includeallmagnitudes] [includeallorigins] [includearrivals]\
    \ [includeallstationsmagnitudes] [format-option]\n\n```\n\n\nwhere\n\n```\n\n\
    id-options              ::  eventid= OR originid= OR magnitudeid= OR focalmechanismid=\n\
    \ngeographic-constraints  ::  [boundaries-rect] OR [boundaries-radial]\n\nboundaries-rect\
    \         ::  [minlat=] [maxlat=] [minlon=] [maxlon=]\n\nboundaries-radial   \
    \    ::  [lat=&lon=&(maxradius= | maxradiuskm=)] [minradius= | minradiuskm=]\n\
    \ndepth-constraints       ::  [mindepth=] [maxdepth=]\n\ntemporal-constraints\
    \    ::  [starttime=] [endtime=]\n\nmagnitude-constraints   ::  [minmag=] [maxmag=]\
    \ [magnitudetype=]\n\nmisc-parameters         ::  [limit=] [offset=] [orderby=]\
    \ [includeallmagnitude=] \n                            [includearrivals=] [includeallorigins=]\
    \ [includeallstationsmagnitudes=]\nformat-option           ::  [format=]\n\n\n\
    \  (..) required parameter\n  [..] optional parameter\n``` \n\n\n# Sample Queries:\n\
    \  - [http://webservices.ingv.it/fdsnws/event/1/query?starttime=2012-05-29T00:00:00&endtime=2012-05-29T23:59:59](http://webservices.ingv.it/fdsnws/event/1/query?starttime=2012-05-29T00:00:00&endtime=2012-05-29T23:59:59)\n\
    \  - [http://webservices.ingv.it/fdsnws/event/1/query?starttime=2010-05-29T00:00:00&endtime=2012-05-29T23:59:58&limit=10&offset=2](http://webservices.ingv.it/fdsnws/event/1/query?starttime=2010-05-29T00:00:00&endtime=2012-05-29T23:59:58&limit=10&offset=2)\n\
    \  - [http://webservices.ingv.it/fdsnws/event/1/query?starttime=2012-05-29T00:00:00&endtime=2012-05-29T23:59:59&format=text](http://webservices.ingv.it/fdsnws/event/1/query?starttime=2012-05-29T00:00:00&endtime=2012-05-29T23:59:59&format=text)\
    \ (text format)\n  - [http://webservices.ingv.it/fdsnws/event/1/query?eventId=841091&includeallmagnitudes=true&includeallorigins=true&includearrivals=true&includeallstationsmagnitudes=true](http://webservices.ingv.it/fdsnws/event/1/query?eventId=841091&includeallmagnitudes=true&includeallorigins=true&includearrivals=true&includeallstationsmagnitudes=true)\n\
    \n\n Find out more about FDSN Web Service Specifications http://www.fdsn.org/webservices/"
  license:
    name: Creative Commons Attribution 4.0 International
    url: http://creativecommons.org/licenses/by/4.0/
  termsOfService: http://www.fdsn.org/webservices/
  title: INGV ONT FDSNWS event Web Service Documentation
  version: 1.1.50
  x-api-id: FIXME an uuidgen for this API
  x-lifecycle:
    maturity: FIXME
  x-summary: FIXME oneliner for catalog purposes
servers:
- name: Production
  url: http://webservices.ingv.it/fdsnws/event/1
tags:
- description: ''
  externalDocs:
    description: Find out more
    url: https://quake.ethz.ch/quakeml/
  name: fdsnws-event-1.1
paths:
  /application.wadl:
    get:
      description: Returns application.wadl file content
      responses:
        '200':
          content:
            application/xml:
              schema:
                additionalProperties:
                  format: int32
                  type: integer
                type: object
          description: successful operation
      summary: Get application.wadl
      tags:
      - fdsnws-event-1.1
  /query:
    get:
      description: Returns a QuakeML message with the following schema https://quake.ethz.ch/quakeml/
      parameters:
      - description: Limit to events that are active on or after the specified start
          time. - [ **YYYY-MM-DDThh:mm:ss** | **YYYY-MM-DD** ] (ex. 2013-02-18T15:06:38)
        in: query
        name: starttime
        required: false
        schema:
          format: date-time
          items:
            type: string
          type: string
      - description: Limit to events that are active on or before the specified end
          time. - [ **YYYY-MM-DDThh:mm:ss** | **YYYY-MM-DD** ] (ex. 2013-02-19T17:06:38)
        in: query
        name: endtime
        required: false
        schema:
          format: date-time
          items:
            type: string
          type: string
      - description: Specify southern boundary for search.
        in: query
        name: minlat
        required: false
        schema:
          format: double
          items:
            type: string
          type: number
      - description: Specify northern boundary for search.
        in: query
        name: maxlat
        required: false
        schema:
          format: double
          items:
            type: string
          type: number
      - description: Specify western boundary for search.
        in: query
        name: minlon
        required: false
        schema:
          format: double
          items:
            type: string
          type: number
      - description: Specify eastern boundary for search.
        in: query
        name: maxlon
        required: false
        schema:
          format: double
          items:
            type: string
          type: number
      - description: Specify the central latitude point for a radial search.
        in: query
        name: lat
        required: false
        schema:
          format: double
          items:
            type: string
          type: number
      - description: Specify the central longitude point for a radial search.
        in: query
        name: lon
        required: false
        schema:
          format: double
          items:
            type: string
          type: number
      - description: Specify minimum distance from the geographic point defined by
          latitude and longitude. Degrees.
        in: query
        name: minradius
        required: false
        schema:
          format: double
          items:
            type: string
          type: number
      - description: Specify maximum distance from the geographic point defined by
          latitude and longitude. Degrees.
        in: query
        name: maxradius
        required: false
        schema:
          format: double
          items:
            type: string
          type: number
      - description: Specify minimum distance from the geographic point defined by
          latitude and longitude. Kilometers. **This is an INGV extension to the FDSN
          specification.**
        in: query
        name: minradiuskm
        required: false
        schema:
          format: double
          items:
            type: string
          type: number
      - description: Specify maximum distance from the geographic point defined by
          latitude and longitude. Kilometers. **This is an INGV extension to the FDSN
          specification.**
        in: query
        name: maxradiuskm
        required: false
        schema:
          format: double
          items:
            type: string
          type: number
      - description: Specify minimum depth (kilometers), values increase positively
          with depth. Degrees.
        in: query
        name: mindepth
        required: false
        schema:
          format: double
          items:
            type: string
          type: number
      - description: Specify maximum depth (kilometers), values increase positively
          with depth. Degrees.
        in: query
        name: maxdepth
        required: false
        schema:
          format: double
          items:
            type: string
          type: number
      - description: Is used to order the output.
        in: query
        name: orderby
        required: false
        schema:
          default: time
          enum:
          - time
          - time-asc
          - magnitude
          - magnitude-asc
          items:
            type: string
          type: string
      - description: Limit the results to the specified number of events.
        in: query
        name: limit
        required: false
        schema:
          format: integer
          items:
            type: string
          type: number
      - description: Return results starting at the event count specified.
        in: query
        name: offset
        required: false
        schema:
          format: integer
          items:
            type: string
          type: number
      - description: Limit to events updated after the specified time (useful for
          synchronizing events).
        in: query
        name: updatedafter
        required: false
        schema:
          format: date-time
          items:
            type: string
          type: string
      - description: Specify output format.
        in: query
        name: format
        required: false
        schema:
          default: xml
          enum:
          - xml
          - text
          items:
            type: string
          type: string
      - description: Retrieve an event based on the unique INGV event id.
        in: query
        name: eventid
        required: false
        schema:
          items:
            type: integer
          type: integer
      - description: Is used to retrive all origins associated with each event.
        in: query
        name: includeallorigins
        required: false
        schema:
          default: false
          items:
            type: boolean
          type: boolean
      - description: Is used to retrive all magnitudes associated with each event.
        in: query
        name: includeallmagnitudes
        required: false
        schema:
          default: false
          items:
            type: boolean
          type: boolean
      - description: Is used to retrive all stations magnitudes associated with each
          hypocenter.
        in: query
        name: includeallstationsmagnitudes
        required: false
        schema:
          default: false
          items:
            type: boolean
          type: boolean
      - description: Is used to retrive any associated phase arrival information for
          each event.
        in: query
        name: includearrivals
        required: false
        schema:
          default: false
          items:
            type: boolean
          type: boolean
      responses:
        '200':
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/QuakeMLResponse'
            text/plain:
              schema:
                $ref: '#/components/schemas/QuakeMLResponse'
          description: Successful request, results follow
          headers:
            X-RateLimit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
        '204':
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Request was properly formatted and submitted but no data matches
            the selection
        '400':
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad request due to improper specification, unrecognized parameter,
            parameter value out of range, etc.
        '401':
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Unauthorized, authentication required
        '403':
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Authentication failed or access blocked to restricted data
        '404':
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Alternate to 204 (set via the 'nodata' parameter), normally
            used for results returned to a web browser.
        '413':
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Request would result in too much data being returned or the
            request itself is too large returned error message should include the
            service limitations in the detailed description. Service limits should
            also be documented in the service WADL.
        '414':
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Request URI too large
        429TooManyRequests:
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
          description: Too many requests
          headers:
            Retry-After:
              $ref: '#/components/headers/Retry-After'
            X-RateLimit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
        '500':
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal server error
        '503':
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            text/plain:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Service temporarily unavailable, used in maintenance and error
            conditions
        default:
          description: ''
      summary: Get QuakeML
      tags:
      - fdsnws-event-1.1
  /version:
    get:
      description: Returns a string containing QuakeML version
      responses:
        '200':
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/VersionResponse'
          description: successful operation
      summary: Get QuakeML version
      tags:
      - fdsnws-event-1.1
components:
  headers:
    Retry-After:
      description: |-
        Retry contacting the endpoint *at least* after seconds.
        See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        format: int32
        type: integer
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period
      schema:
        format: int32
        type: integer
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period
      schema:
        format: int32
        type: integer
    X-RateLimit-Reset:
      description: The number of seconds left in the current period
      schema:
        format: int32
        type: integer
  schemas:
    ErrorResponse:
      example: 'Error CODE: SIMPLE ERROR DESCRIPTION ...'
      type: string
    Problem:
      properties:
        detail:
          description: |
            A human readable explanation specific to this occurrence of the
            problem. You MUST NOT expose internal informations, personal
            data or implementation details through this field.
          example: Request took too long to complete.
          type: string
        instance:
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
          format: uri
          type: string
        status:
          description: |
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          example: 503
          exclusiveMaximum: true
          format: int32
          maximum: 600
          minimum: 100
          type: integer
        title:
          description: |
            A short, summary of the problem type. Written in english and readable
            for engineers (usually not suited for non technical stakeholders and
            not localized); example: Service Unavailable
          type: string
        type:
          default: about:blank
          description: |
            An absolute URI that identifies the problem type.  When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          example: https://tools.ietf.org/html/rfc7231#section-6.6.4
          format: uri
          type: string
      type: object
    QuakeMLResponse:
      xml:
        namespace: https://quake.ethz.ch/quakeml/
    VersionResponse:
      example: 1.1.50
      type: string
